PIPELINE_STATUS_STARTING = "starting"
PIPELINE_STATUS_RUNNING = "run"
PIPELINE_STATUS_STOPPING = "stopping"
PIPELINE_STATUS_STOPPED = "stop"

SOURCE_STATUS_CONNECTED = "connected"
SOURCE_STATUS_DISCONNECTED = "disconnected"
